export const seedData = {
  tenants: [
    {
      slug: 'acme-manufacturing',
      name: 'ACME Manufacturing Co.',
      description: 'Leading manufacturer of industrial equipment',
      website: 'https://acme-mfg.example.com',
      subdomain: 'acme',
      settings: {
        timezone: 'America/New_York',
        dateFormat: 'MM/DD/YYYY',
        currency: 'USD',
        language: 'en',
      },
      billing: {
        plan: 'enterprise',
        seats: 100,
        billingCycle: 'monthly',
      },
      isActive: true,
    },
    {
      slug: 'demo-factory',
      name: 'Demo Factory Inc.',
      description: 'Demo tenant for testing',
      subdomain: 'demo',
      settings: {
        timezone: 'UTC',
        dateFormat: 'YYYY-MM-DD',
        currency: 'EUR',
        language: 'en',
      },
      billing: {
        plan: 'starter',
        seats: 10,
        billingCycle: 'monthly',
      },
      isActive: true,
    },
  ],
  departments: [
    {
      code: 'PROD',
      name: 'Production',
      description: 'Main production department',
      location: 'Building A',
      costCenter: 'CC-1000',
    },
    {
      code: 'QA',
      name: 'Quality Assurance',
      description: 'Quality control and testing',
      location: 'Building A',
      costCenter: 'CC-2000',
    },
    {
      code: 'MAINT',
      name: 'Maintenance',
      description: 'Equipment maintenance department',
      location: 'Building B',
      costCenter: 'CC-3000',
    },
    {
      code: 'WHSE',
      name: 'Warehouse',
      description: 'Inventory and logistics',
      location: 'Building C',
      costCenter: 'CC-4000',
    },
  ],
  roles: [
    {
      name: 'Administrator',
      code: 'ADMIN',
      description: 'Full system access',
      permissions: { all: true },
      isSystem: true,
    },
    {
      name: 'Production Manager',
      code: 'PROD_MGR',
      description: 'Manages production operations',
      permissions: { production: ['read', 'write', 'delete'] },
      isSystem: false,
    },
    {
      name: 'Quality Inspector',
      code: 'QA_INSP',
      description: 'Performs quality inspections',
      permissions: { quality: ['read', 'write'] },
      isSystem: false,
    },
    {
      name: 'Machine Operator',
      code: 'OPERATOR',
      description: 'Operates production equipment',
      permissions: { tasks: ['read', 'update'] },
      isSystem: false,
    },
  ],
  users: [
    {
      email: 'admin@acme-mfg.com',
      username: 'admin',
      firstName: 'System',
      lastName: 'Administrator',
      phone: '555-0100',
      position: 'System Administrator',
      employeeId: 'EMP001',
      departmentIndex: 0,
      status: 'active' as const,
      preferences: { theme: 'light', notifications: true },
    },
    {
      email: 'john.smith@acme-mfg.com',
      username: 'jsmith',
      firstName: 'John',
      lastName: 'Smith',
      phone: '555-0101',
      position: 'Production Manager',
      employeeId: 'EMP002',
      departmentIndex: 0,
      status: 'active' as const,
    },
    {
      email: 'jane.doe@acme-mfg.com',
      username: 'jdoe',
      firstName: 'Jane',
      lastName: 'Doe',
      phone: '555-0102',
      position: 'Quality Inspector',
      employeeId: 'EMP003',
      departmentIndex: 1,
      status: 'active' as const,
    },
    {
      email: 'bob.wilson@acme-mfg.com',
      username: 'bwilson',
      firstName: 'Bob',
      lastName: 'Wilson',
      phone: '555-0103',
      position: 'Machine Operator',
      employeeId: 'EMP004',
      departmentIndex: 0,
      status: 'active' as const,
    },
  ],
  userRoles: [
    { userIndex: 0, roleIndex: 0, assignedByIndex: 0 },
    { userIndex: 1, roleIndex: 1, assignedByIndex: 0 },
    { userIndex: 2, roleIndex: 2, assignedByIndex: 0 },
    { userIndex: 3, roleIndex: 3, assignedByIndex: 1 },
  ],
  uoms: [
    {
      code: 'PCS',
      name: 'Pieces',
      description: 'Individual pieces',
      category: 'quantity' as const,
      symbol: 'pcs',
      conversionFactor: 1,
      decimalPlaces: 0,
    },
    {
      code: 'KG',
      name: 'Kilogram',
      description: 'Weight in kilograms',
      category: 'weight' as const,
      symbol: 'kg',
      conversionFactor: 1,
      decimalPlaces: 2,
    },
    {
      code: 'M',
      name: 'Meter',
      description: 'Length in meters',
      category: 'length' as const,
      symbol: 'm',
      conversionFactor: 1,
      decimalPlaces: 2,
    },
    {
      code: 'L',
      name: 'Liter',
      description: 'Volume in liters',
      category: 'volume' as const,
      symbol: 'L',
      conversionFactor: 1,
      decimalPlaces: 2,
    },
    {
      code: 'HR',
      name: 'Hour',
      description: 'Time in hours',
      category: 'time' as const,
      symbol: 'hr',
      conversionFactor: 1,
      decimalPlaces: 2,
    },
  ],
  categories: [
    {
      code: 'FIN',
      name: 'Finished Goods',
      description: 'Completed products ready for sale',
      sortOrder: 1,
    },
    {
      code: 'SEMI',
      name: 'Semi-Finished Goods',
      description: 'Partially completed products',
      sortOrder: 2,
    },
    {
      code: 'RAW',
      name: 'Raw Materials',
      description: 'Basic materials for production',
      sortOrder: 3,
    },
    {
      code: 'COMP',
      name: 'Components',
      description: 'Component parts',
      sortOrder: 4,
    },
  ],
  products: [
    {
      sku: 'WIDGET-001',
      name: 'Industrial Widget A',
      description: 'High-performance industrial widget',
      type: 'manufactured' as const,
      categoryIndex: 0,
      uomIndex: 0,
      specifications: {
        weight: '2.5 kg',
        dimensions: '10x10x5 cm',
        material: 'Steel',
      },
      standardCost: 150.00,
      listPrice: 250.00,
      isActive: true,
    },
    {
      sku: 'GADGET-001',
      name: 'Premium Gadget X',
      description: 'Advanced electronic gadget',
      type: 'manufactured' as const,
      categoryIndex: 0,
      uomIndex: 0,
      specifications: {
        weight: '1.2 kg',
        power: '12V DC',
      },
      standardCost: 200.00,
      listPrice: 350.00,
      isActive: true,
    },
    {
      sku: 'SUB-ASM-001',
      name: 'Sub-Assembly Module A',
      description: 'Core sub-assembly module',
      type: 'manufactured' as const,
      categoryIndex: 1,
      uomIndex: 0,
      standardCost: 50.00,
      listPrice: 0,
      isActive: true,
    },
    {
      sku: 'STEEL-SHEET-001',
      name: 'Steel Sheet 2mm',
      description: '2mm thick steel sheet',
      type: 'purchased' as const,
      categoryIndex: 2,
      uomIndex: 1,
      standardCost: 25.00,
      listPrice: 0,
      isActive: true,
    },
    {
      sku: 'PLASTIC-RESIN-001',
      name: 'ABS Plastic Resin',
      description: 'ABS thermoplastic resin',
      type: 'purchased' as const,
      categoryIndex: 2,
      uomIndex: 1,
      standardCost: 5.00,
      listPrice: 0,
      isActive: true,
    },
    {
      sku: 'SCREW-M6-20',
      name: 'M6x20 Hex Screw',
      description: 'Metric hex screw M6x20mm',
      type: 'purchased' as const,
      categoryIndex: 3,
      uomIndex: 0,
      standardCost: 0.10,
      listPrice: 0,
      isActive: true,
    },
    {
      sku: 'BEARING-6204',
      name: 'Ball Bearing 6204',
      description: 'Deep groove ball bearing',
      type: 'purchased' as const,
      categoryIndex: 3,
      uomIndex: 0,
      standardCost: 8.00,
      listPrice: 0,
      isActive: true,
    },
  ],
};